services:
  awayhome-ui:
    build: ./awayhome-ui
    ports:
      - "3001:3000"
    env_file:
      - .env
    volumes:
      - ./awayhome-ui:/app
    command: ["npm", "run", "dev"]

  awayhome-api:
    build: ./awayhome-api
    ports:
      - "5001:5000"
    env_file:
      - .env
    volumes:
      - ./awayhome-api:/app
    depends_on:
      - awayhome-db
    command: ["npm", "run", "dev"]

  awayhome-db:
    image: postgres:13
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${AWH_PG_DATABASE}
      POSTGRES_USER: ${AWH_PG_USER}
      POSTGRES_PASSWORD: ${AWH_PG_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
