services:
  awayhome-ui:
    build: ./awayhome-ui
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_AWH_API_URL=${NEXT_PUBLIC_AWH_API_URL}
      - NEXT_PUBLIC_FIREBASE_API_KEY=${NEXT_PUBLIC_FIREBASE_API_KEY}
      - NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}
      - NEXT_PUBLIC_FIREBASE_PROJECT_ID=${NEXT_PUBLIC_FIREBASE_PROJECT_ID}
      - NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}
      - NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}
      - NEXT_PUBLIC_FIREBASE_APP_ID=${NEXT_PUBLIC_FIREBASE_APP_ID}
      - NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}
      - UI_PORT=${UI_PORT}
    volumes:
      - ./awayhome-ui:/app
    command: ["npm", "run", "dev"]

  awayhome-api:
    build: ./awayhome-api
    ports:
      - "5001:5000"
    environment:
      - NODE_ENV=development
      - PORT=${API_PORT}
      - AWH_MYSQL_HOST=awayhome-db
      - AWH_MYSQL_ROOT_PASSWORD=${AWH_MYSQL_ROOT_PASSWORD}
      - AWH_MYSQL_DATABASE=${AWH_MYSQL_DATABASE}
      - AWH_MYSQL_USER=${AWH_MYSQL_USER}
      - AWH_MYSQL_PASSWORD=${AWH_MYSQL_PASSWORD}
      - FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_MESSAGING_SENDER_ID}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}
      - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
      - AWAYHOME_API_KEY=${AWAYHOME_API_KEY}
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
      - API_PORT=${API_PORT}
    volumes:
      - ./awayhome-api:/app
    depends_on:
      - awayhome-db

    command: ["npm", "run", "dev"]

  awayhome-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${AWH_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${AWH_MYSQL_DATABASE}
      MYSQL_USER: ${AWH_MYSQL_USER}
      MYSQL_PASSWORD: ${AWH_MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - awh-mysql-data:/var/lib/mysql
      - ./awayhome-api/sql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  awh-mysql-data:
