jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 3307:3306 # Example for DB
          - 3001:3000 # Example for UI
          - 5001:5000 # Example for API
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and Start Docker Compose
        run: |
          docker-compose down
          docker-compose up --build -d
        env:
          AWH_MYSQL_ROOT_PASSWORD: ${{ secrets.AWH_MYSQL_ROOT_PASSWORD }}
          AWH_MYSQL_DATABASE: ${{ secrets.AWH_MYSQL_DATABASE }}
          AWH_MYSQL_USER: ${{ secrets.AWH_MYSQL_USER }}
          AWH_MYSQL_PASSWORD: ${{ secrets.AWH_MYSQL_PASSWORD }}
          AWH_API_URL: ${{ secrets.AWH_API_URL }}
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
          FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}

      - name: Run backend tests
        run: docker-compose exec awayhome-api npm test

      - name: Run frontend tests
        run: docker-compose exec awayhome-ui npm test

      - name: Tear down Docker Compose
        run: docker-compose down
